version: '2'
services:
        product_service:
                build: ./product_service
                ports:
                        - "8101:8101"
                depends_on:
                        - db
                environment:
                        - DATABASE_HOST=db
        db:
                build: ./test-database
